### ISSUE TITLE
Make bot respond to command messages

### ISSUE THREAD

**Issue by XaverStiensmeier** [XaverStiensmeier/ilarisdiscordbot#42]
It would be nice if the bot would use the "reply" function to directly reply to the message that triggered him. That way it would be easier to see to whom the bot refers using "du" "deine" and so on.

**Comment by tacosontitan** [comment]
I'll take a look at this 😄

**Comment by tacosontitan** [comment]
I'm sorry, but something came up and I will not be able to work this adequately. It should be a straightforward adjustment for potential future contributors, however:

https://discordpy.readthedocs.io/en/stable/ext/commands/api.html?highlight=reply#discord.ext.commands.Context.reply

Best of luck with your project!
