### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by lukruh** [XaverStiensmeier/ilarisdiscordbot#54]
looks like most of the messages and commands are in english yet. A big part of the community is probably german. Might be a bit overkill, but we could think about putting all the messages into a seperate yaml file and add a language code to the bot config. The different languages could just update the base file so that everything works even with incomplete translation.. and translations could be added without touching the source code.

Somthing like: `config/messages.yml`, `config/messages_de.yml` with

```python
msgs = load_config('messages.yml')
try:
    msgs.update(load_config(f"messages_{config['language'].yml"))
```

we could also use something like https://docs.python.org/3/library/gettext.html but I think thats way too heavy for listing a couple of messages in 2 languages.

## Progress: 

- [x] move all strings from code into yml file
- [x] create a translated messages_de.yml
- [x] load messages based on configured language
- [ ] create german readme file?
- [ ] dynamically create bot commands to support german commands with english aliases as well?

**Comment by XaverStiensmeier** [comment]
Yes, this is definitely smart to do. However, currently it doesn't have a high priority for me.

**Comment by lukruh** [comment]
I added a minimal example for two simple commands. If you like that approach I can do it for all strings in all commands:
https://github.com/XaverStiensmeier/ilarisdiscordbot/pull/59/commits/5542d882d7af16efd2587cb1e0b814b1819336c5
