### ISSUE TITLE
No channel update on destroy

### ISSUE THREAD

**Issue by lukruh** [XaverStiensmeier/ilarisdiscordbot#72]
when a new group is created the message in the configured info channel is updated, but not when its destroyed. Is that intended? I'd say it should be updated in both cases.

**Comment by XaverStiensmeier** [comment]
no, it should be updated, too.

**Comment by lukruh** [comment]
cant find where this update is triggered.. if you point me to the code snippet how its done for new groups I can add it for removed groups in #73

**Comment by XaverStiensmeier** [comment]
Take a look here: https://github.com/XaverStiensmeier/ilarisdiscordbot/blob/main/ilaris_bot.py#L84C1-L94C52

I see no immediate reason why it is not triggered for `gdestroy`. This is definitely a bug - probably on our side.

**Comment by lukruh** [comment]
I will play around with it as soon as I have my dev bot running. Don't want to spam the con server too much.

**Comment by lukruh** [comment]
I might have deleted the group in private chat or somewhere where it did not find the guild correctly.. I think it can be closed for now
